[package]
name = "gif_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy_ecs = "0.17.3"
bevy_egui = "0.38.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
reqwest = { version = "0.12.24", features = ["json", "blocking", "stream"] }
image = "0.25.8"
gif-dispose = "5.0.1"
gif = "0.13.3"
futures-util = "0.3.31"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
winit = "0.30.11"